- name: Criando partição files
  parted:
    label: gpt
    device: /dev/sda
    number: 1
    state: present

- name: Create or resize a volume group on top of /dev/sda1.
  lvg:
    vg: vgansible
    pvs: /dev/sda1

- name: Create a logical volume the size of all remaining space in the volume group
  lvol:
    vg: vgansible
    lv: lvansible
    size: 100%FREE

- name: Create a xfs filesystem on /dev/mapper/vgansible-lvansible
  filesystem:
    fstype: xfs
    dev: /dev/vgansible/lvansible